on:
  pull_request:
    types:
      - closed
    branches:
      - master
jobs:
  if_merged:
    runs-on: [self-hosted, Linux, x64]
    if: github.event.pull_request.merged == true
    steps:
      - name: Go to project dir
        run: cd /home/jsilvab/dev/test-git/pullrequest-test
      - name: Checout Master Branch
        run: git checkout master
      - name: Pull code from master
        run: git pull
