on:
  pull_request:
    - types: closed

jobs:
  if_merged:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-22.04
    steps:
      - run: |
        git checkout master && git pull
